# Generated by Django 3.2.6 on 2022-01-04 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_autor', models.CharField(max_length=30)),
                ('prenume_autor', models.CharField(max_length=30)),
                ('tara_origine', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=30)),
                ('adresa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=200)),
                ('editura', models.CharField(max_length=50)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.autor')),
                ('id_biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.biblioteca')),
            ],
        ),
    ]
