# Generated by Django 3.2.6 on 2022-01-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='denumire',
            field=models.CharField(max_length=100),
        ),
    ]
