# Generated by Django 3.2.6 on 2022-01-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_biblioteca_denumire'),
    ]

    operations = [
        migrations.AddField(
            model_name='carti',
            name='an_aparitie',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
