# Generated by Django 3.2.6 on 2022-01-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_carti_an_aparitie'),
    ]

    operations = [
        migrations.AddField(
            model_name='carti',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
