# Generated by Django 3.2.6 on 2022-01-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_carti_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carti',
            name='id_autor',
        ),
        migrations.AddField(
            model_name='carti',
            name='id_autor',
            field=models.ManyToManyField(to='book.Autor'),
        ),
        migrations.RemoveField(
            model_name='carti',
            name='id_biblioteca',
        ),
        migrations.AddField(
            model_name='carti',
            name='id_biblioteca',
            field=models.ManyToManyField(blank=True, to='book.Biblioteca'),
        ),
    ]
