# Generated by Django 3.2.6 on 2022-01-06 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_notifications',
        ),
    ]
