# Generated by Django 3.2.6 on 2022-01-06 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_remove_profile_email_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
