# Generated by Django 3.2.6 on 2022-01-06 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carti',
            options={'permissions': [('can_delete_books', 'You can delete books.')]},
        ),
    ]
