# Generated by Django 3.2.6 on 2022-01-08 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_auto_20220107_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='biblioteca',
            options={},
        ),
        migrations.AlterModelOptions(
            name='carti',
            options={},
        ),
    ]
